### ISSUE TITLE
Search | Multiple quick refreshes

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#1]
When a term is entered into the search bar and enter key pressed, there are quick changes in the top results. It's a bit jarring. 
![A6YRcaT5gc](https://user-images.githubusercontent.com/64309749/124573371-1c233800-de67-11eb-90be-b2e93b31735f.gif)
@PixeledCode

**Comment by PixeledCode** [comment]
fixed with Meilisearch
