### ISSUE TITLE
Search | A few search results don't get redirected to the content

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#2]
When I searched for `municipality` and clicked on the first search result, it didn't redirect to the content. Stayed on the homepage itself. 

![ZHW36LM65I](https://user-images.githubusercontent.com/64309749/124573846-8805a080-de67-11eb-9d0e-3145375ba030.gif)

**Comment by PixeledCode** [comment]
This issue arises when there is no chapter assigned when creating an article in strapi. Fixed
