### ISSUE TITLE
Search | The search bar on the top right corner of the chapters pages giving different results

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#4]
The search bar in the inner pages also has the same problem as #1. Additionally, it's giving different results from the main search bar. 

![HcQtw0TI8q](https://user-images.githubusercontent.com/64309749/124575363-f8f98800-de68-11eb-9649-afb1f0a3b029.gif)

**Comment by PixeledCode** [comment]
fixed in the latest build. created a centralized search component
