### ISSUE TITLE
Navigation | Should the header stay when scrolling?

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#5]
While scrolling down chapters which are quite long, there's no easy way to go back to the main menu except use the browsers back button or scroll all the way up to the header. Should the header stay while the content scrolls? 

![6ZO2jmaYYm](https://user-images.githubusercontent.com/64309749/124575870-65748700-de69-11eb-9954-1817ce116ef3.gif)

**Comment by PixeledCode** [comment]
will need input from @SuchismitaNaik regarding this

**Comment by PixeledCode** [comment]
added a 'go-to top' button to scroll back to top
