### ISSUE TITLE
Mobile | Homepage not scaling well to a mobile screen

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#6]
Device: iPhone 6, Browser: Firefox (however, since all browsers on iOS uses the same WebKit engine, results are similar). 

Homepage is not scaling well on a mobile screen. 

![Image_2](https://user-images.githubusercontent.com/64309749/124586158-be491d00-de73-11eb-8909-bd43fc1f5eb8.GIF)

**Comment by PixeledCode** [comment]
fixed in the latest build
