### ISSUE TITLE
Mobile | Search on homepage broken

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#7]
Device: iPhone 6, Browser: Firefox (however, since all browsers on iOS uses the same Webkit engine, results are similar). 

![Image_3](https://user-images.githubusercontent.com/64309749/124586473-1a13a600-de74-11eb-947e-ae5f28dff944.GIF)

**Comment by PixeledCode** [comment]
fixed in the latest build. Issue: clamp() not supported on older ios
