### ISSUE TITLE
Mobile | Long section names not working well on mobile screen

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#8]
Device: iPhone 6, Browser: Firefox (however, since all browsers on iOS uses the same Webkit engine, results are similar). 

![Image_1](https://user-images.githubusercontent.com/64309749/124586611-44fdfa00-de74-11eb-9841-dffa10b7f4ef.GIF)

**Comment by PixeledCode** [comment]
fixed in latest build
