### ISSUE TITLE
Mobile | Section names are small. Difficult to accurately touch and select the desired one

### ISSUE THREAD

**Issue by arunsud** [cbgaindia/budget-basic-next#9]
Device: iPhone 6, Browser: Firefox (however, since all browsers on iOS uses the same Webkit engine, results are similar). 

![Image](https://user-images.githubusercontent.com/64309749/124586721-6bbc3080-de74-11eb-92a4-7a34a1e65c9c.GIF)

**Comment by PixeledCode** [comment]
fixed in the latest build. Added padding and increased font size
